### ISSUE TITLE
可能的链接问题

### ISSUE THREAD

**Issue by Higurashi-kagome** [Liiked/VS-Code-Extension-Doc-ZH#101]
[◼️预备知识=>认识TypeScript-变量和类型=>类型：](https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/preknowledge/variable-and-type?id=%e7%b1%bb%e5%9e%8b)

“变量声明的基础规则请自行参考JavaScript...，有关分号风格，**请参阅**。”

“请参阅”之后似乎遗漏了链接。

**Comment by Higurashi-kagome** [comment]
补充：

[◼️预备知识=>认识TypeScript-变量和类型=>变量声明=>let声明：](https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/preknowledge/variable-and-type?id=let%e5%a3%b0%e6%98%8e)

“由于本章侧重于帮助读者流畅地阅读文档中出现的TS代码，因此本节不再赘述var和新关键字之间的区别，读者如有兴趣可自行参考[TypeScript文档](https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/)。”

此处的链接似乎错误地指向了本教程的主页（`https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/`）。

**Comment by Higurashi-kagome** [comment]
[◼️预备知识=>非JS开发者的第一步=>认识Typescript-变量和类型=>认识Typescript-类=>下一步](https://liiked.github.io/VS-Code-Extension-Doc-ZH/?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied#/preknowledge/class?id=%e4%b8%8b%e4%b8%80%e6%ad%a5)：

- [泛型和命名空间](https://liiked.github.io/VS-Code-Extension-Doc-ZH/?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied#/preknowledge/generics-and-modules) - 进一步了解Typescript所规定的语法。

访问链接显示“404 - Not found”。

**Comment by Liiked** [comment]
非常感谢我们会尽快修复这些问题

**Comment by Liiked** [comment]
https://github.com/Liiked/VS-Code-Extension-Doc-ZH/pull/110
