### ISSUE TITLE
可能的示例错误

### ISSUE THREAD

**Issue by Higurashi-kagome** [Liiked/VS-Code-Extension-Doc-ZH#102]
**模板字符串示例**

[◼️预备知识=>认识Typescript-变量和类型=>类型=>字符串](https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/preknowledge/variable-and-type?id=%e5%ad%97%e7%ac%a6%e4%b8%b2)中有这样一段说明：

<details>
<summary>Details</summary>

你还可以使用模版字符串，它可以定义多行文本和内嵌表达式。 这种字符串是被反引号包围（ \`），并且以`${ expr }`这种形式嵌入表达式

```TypeScript
let name: string = `Gene`;
let age: number = 37;
let sentence: string = `Hello, my name is ${ name }.
I'll be ${ age + 1 } years old next month.`;
```

这与下面定义`sentence`的方式效果相同：

```TypeScript
let sentence: string = "Hello, my name is " + name + ".\n\n" +
    "I'll be " + (age + 1) + " years old next month.";
```

</details>

<hr>

而实际结果并不相同（似乎是因该段说明中的第二段代码中多加了一个换行符）。

以下为我的测试：

<details>
<summary>Test code</summary>

```TypeScript
let aName: string = `Gene`;
let age: number = 37;
let sentence1: string = `Hello, my name is ${ aName }.
I'll be ${ age + 1 } years old next month.`;
console.log(sentence1);

let sentence2: string = "Hello, my name is " + aName + ".\n\n" +
    "I'll be " + (age + 1) + " years old next month.";
console.log(sentence2);
```

</details>

<details>
<summary>Output</summary>

```
Hello, my name is Gene.
I'll be 38 years old next month.
Hello, my name is Gene.

I'll be 38 years old next month.
```

</details>

**Comment by Liiked** [comment]
非常感谢我们会尽快修复这些问题

**Comment by Liiked** [comment]
https://github.com/Liiked/VS-Code-Extension-Doc-ZH/pull/110
