### ISSUE TITLE
可能的笔误

### ISSUE THREAD

**Issue by Higurashi-kagome** [Liiked/VS-Code-Extension-Doc-ZH#103]
[◼️开发插件=>测试插件=>概述=>测试入口](https://liiked.github.io/VS-Code-Extension-Doc-ZH/?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied#/working-with-extensions/testing-extension?id=%e6%b5%8b%e8%af%95%e5%85%a5%e5%8f%a3)下的 `测试入口（src/test/runTest.ts））使用了vscode-testAPI，简化了下载...` 中多了一个右括号（`）`）。

**Comment by Liiked** [comment]
非常感谢我们会尽快修复这些问题

**Comment by Higurashi-kagome** [comment]
[加载本地内容](https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/extension-guides/webview?id=%e6%88%91%e5%ba%94%e8%af%a5%e7%94%a8webview%e5%90%97%ef%bc%9f) ：

**想想**一下，我们想要从本地把喵喵们的 gif 打包进来...

**Comment by Liiked** [comment]
https://github.com/Liiked/VS-Code-Extension-Doc-ZH/pull/110
