### ISSUE TITLE
纠错

### ISSUE THREAD

**Issue by l3-arch** [Liiked/VS-Code-Extension-Doc-ZH#108]
认识Typescript-类 -> 修饰符 -> static 
中的代码演示
class Router {
    static baseRoute = '/basePath';
    calculateRoute(path: string) {
        return this.baseRoute + this.commonPrefix  + path; // 应该是 Router.baseRoute
    }
    constructor (public commonPrefix: number) { } // 应该是 string
}

let route1 = new Router('/api');  // 一级路径为/api
let route2 = new Router('/page');  // 一级路径为/page

console.log(route1.calculateRoute('/main');  // 最终路径/basePath/api/main 少了 )
console.log(route2.calculateRoute('/user');  // 最终路径/basePath/page/user 少了 )

**Comment by Liiked** [comment]
非常感谢你的帮助，我们会尽快处理

**Comment by Liiked** [comment]
https://github.com/Liiked/VS-Code-Extension-Doc-ZH/pull/110
