### ISSUE TITLE
文档内图片似乎404了

### ISSUE THREAD

**Issue by AuTsing** [Liiked/VS-Code-Extension-Doc-ZH#109]

**Comment by Liiked** [comment]
请详细地描述你遇到的问题

**Comment by AuTsing** [comment]
![QQ截图20210301135509](https://user-images.githubusercontent.com/30796735/109457464-dd830880-7a95-11eb-8190-1f72feba9272.png)

![QQ截图20210301135533](https://user-images.githubusercontent.com/30796735/109457457-dbb94500-7a95-11eb-91f9-8cd2dc8dddfc.png)

文档内引用 media.githubusercontent.com 的图片均404了

**Comment by AuTsing** [comment]
好像已经恢复了
