### ISSUE TITLE
除了第一页，其他页面都无法访问

### ISSUE THREAD

**Issue by renyuanzhe** [Liiked/VS-Code-Extension-Doc-ZH#117]
edge，谷歌，火狐都试过了，点击其他页面没有反应

**Comment by Liiked** [comment]
确实出现了很严重的问题，马上会开始修复

**Comment by Liiked** [comment]
> edge，谷歌，火狐都试过了，点击其他页面没有反应

现在可以看看国内加速版的效果了，如果还是没有好，请重开 issue
