### ISSUE TITLE
能否发布一个本地可以直接打开版本

### ISSUE THREAD

**Issue by hongshui3000** [Liiked/VS-Code-Extension-Doc-ZH#125]
好像特别慢网页打开

**Comment by HUGHNew** [comment]
clone 到本地
下载[docsify](https://docsify.js.org/#/quickstart)

然后 进入项目路径
```bash
cd docs
docsify s .
```
或者直接 
```bash
docsify s docs
```

**Comment by HUGHNew** [comment]
```bash
// 本地启动开发
npm i docsify-cli -g
docsify serve docs
```

[这里-issue-104](https://github.com/Liiked/VS-Code-Extension-Doc-ZH/issues/104)提过本地预览
