### ISSUE TITLE
https://vscode-api-cn.js.org/ 求个友链

### ISSUE THREAD

**Issue by youngjuning** [Liiked/VS-Code-Extension-Doc-ZH#134]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/13204332/222633667-7ee21655-5408-4383-a2b6-635946d789fb.png">

**Comment by Liiked** [comment]
首先非常感谢您的认可以及为本项目提供的支持。

我们很高兴也非常珍惜有像您这样的成员，和我们一道为社区内的其他人提供帮助。本项目为保证读者能够顺畅地理解内容并能在阅读过程中获得正确的信息，付出了持久且艰巨的努力。我们希望为读者提供正确的指导，同时也接受读者们的监督，让这份文档为更多的人提供有益的帮助。

该项目始终坚持的原则是1. 为读者提供一致的阅读和理解体验 2. 提供准确易懂的翻译 3. 及时更新内容并保持与主文档同步。为了满足这些原则，本项目统一了术语表、在项目无能为力之处引导读者前往原文档以保证准确性、定期进行更新甚至是大范围重写。因此我们在引用或是使用外部内容时也一致遵守正确性的原则，避免误导读者。目前我们所使用的外部链接都是原文档的内容，大量的 API 引用都流向源文档，这主要出于几方面的原因：1. 本项目无力维护巨量的 API 文档 2. VSC 仍是一个急速发展中的项目，其 API 文档更新速度非常快，同步和审查这类更新需要付出巨大努力。

若本项目能够将文档内各处 API 引用导向本土化的 vscode-api-cn 翻译项目中，是可以很大程度上帮助读者理解内容的，不过这个前提是 vscode-api-cn 与本项目保持着同样的原则和目标，并且 vscode-api-cn 与原文档保持一定的同步程度。但我们发现 vscode-api-cn 中有大量过时或是未翻译的内容，并且术语也并不与本项目保持一致。因此我们怀疑如果目前将链接导向 vscode-api-cn 将会损害读者的阅读体验并违背本项目的原则。但我们仍旧期待 vscode-api-cn 会变得更好，届时若两个项目的目标能够达成一致，本项目也会不惜努力为社区提供更多帮助。

**Comment by zisheng-ai** [comment]
> 首先非常感谢您的认可以及为本项目提供的支持。
> 
> 我们很高兴也非常珍惜有像您这样的成员，和我们一道为社区内的其他人提供帮助。本项目为保证读者能够顺畅地理解内容并能在阅读过程中获得正确的信息，付出了持久且艰巨的努力。我们希望为读者提供正确的指导，同时也接受读者们的监督，让这份文档为更多的人提供有益的帮助。
> 
> 该项目始终坚持的原则是1. 为读者提供一致的阅读和理解体验 2. 提供准确易懂的翻译 3. 及时更新内容并保持与主文档同步。为了满足这些原则，本项目统一了术语表、在项目无能为力之处引导读者前往原文档以保证准确性、定期进行更新甚至是大范围重写。因此我们在引用或是使用外部内容时也一致遵守正确性的原则，避免误导读者。目前我们所使用的外部链接都是原文档的内容，大量的 API 引用都流向源文档，这主要出于几方面的原因：1. 本项目无力维护巨量的 API 文档 2. VSC 仍是一个急速发展中的项目，其 API 文档更新速度非常快，同步和审查这类更新需要付出巨大努力。
> 
> 若本项目能够将文档内各处 API 引用导向本土化的 vscode-api-cn 翻译项目中，是可以很大程度上帮助读者理解内容的，不过这个前提是 vscode-api-cn 与本项目保持着同样的原则和目标，并且 vscode-api-cn 与原文档保持一定的同步程度。但我们发现 vscode-api-cn 中有大量过时或是未翻译的内容，并且术语也并不与本项目保持一致。因此我们怀疑如果目前将链接导向 vscode-api-cn 将会损害读者的阅读体验并违背本项目的原则。但我们仍旧期待 vscode-api-cn 会变得更好，届时若两个项目的目标能够达成一致，本项目也会不惜努力为社区提供更多帮助。

感谢回复，之前这个项目由于管理不善，多人协作的模式进行不下去。中间由于其他事情就搁置了。最近看到谷歌分析的数据竟然还不错，今年打算自己搞起来，借助 AI，也许会轻松许多。
