### ISSUE TITLE
图片全部挂了🤔

### ISSUE THREAD

**Issue by ddzy** [Liiked/VS-Code-Extension-Doc-ZH#39]
如题

**Comment by ddzy** [comment]
> 因vscode 文档官方改版，所有内容正做重新编排，近几天会尽快上新版

很棒!

**Comment by Liiked** [comment]
因为改动内容过多，第二版翻译预计会耗费较长的时间，针对一些迫不及待的小伙伴已经先上了部分翻译

**Comment by Liiked** [comment]
因为改动内容过多，第二版翻译预计会耗费较长的时间，针对一些迫不及待的小伙伴已经先上了部分翻译
